Capstone Project Design [Loom Video]https://www.loom.com/share/f033be45660f4e5cbfd55fb49cbf0769?sid=328402a0-5547-432b-aea3-6a0b5a1b7d7c
Armynerh/html-capstone-project pull request #1
Opened 2023-07-07 15:03 UTC by Armynerh

personalised the content of the page. Chose a topic that is different than the one in the original design.

 followed [design guidelines](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), including:

Colors.
Typography: font face, size and weight (we suggest using [Lato](https://www.latofonts.com/) as it is a free font similar to the one used in the original design).
Layout: composition and space between elements.
The pages looks almost identical to the original design with small adjustments like text and image changes.

built  2 pages:

The home page.
The about page.
Each of these pages  have versions for 2 different screen sizes:

Mobile: up to 768px wide.
Desktop: 768px or wider.
Interactions

Links
The home page has a link in the menu to the about page.
The logo in the header links to the home page.
Mobile menu
When the user clicks (or taps) the hamburger button on the header, the mobile menu appears over the page.
There are no guidelines for the mobile menu in the docs, but I should implement it so it is consistent with the design (colors, typography, spacings, etc.).
The mobile menu has a close (X) button that closes the menu.
Dynamic page

The section "Featured speakers" is created dynamically in JavaScript.
I used a JavaScript variable with the data about the speakers and I used it when the page loads to create the HTML for this section dynamically.
Original design idea by [Cindy Shin in Behance](https://www.behance.net/adagio07).

The [Creative Commons license of the design](https://creativecommons.org/licenses/by-nc/4.0/) requires that I give appropriate credit to the author. Therefore, I added it in the README of my project.

2023-07-07 17:30 UTC, laiifuu requested changes
# STATUS: CHANGES REQUIRED :recycle: 

## Hi @Armynerh :wave:  

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close](https://github.com/Armynerh/html-capstone-project/assets/93520178/ac14b835-bae8-416a-b810-4bcd884fc56a)

## Highlights
- [x] 

## Required Changes ♻️
- [ ] In your README, Kindly remove the section description for the following sections:
    - The key features section: 
    ![image](https://github.com/Armynerh/html-capstone-project/assets/93520178/afd7760b-be3d-47bb-b6ac-e99f556fb8a4)
    - The live demo section: !
    ![image](https://github.com/Armynerh/html-capstone-project/assets/93520178/f858697b-2d66-4e41-b49b-e07afea15e8e)
    - The authors section:
    ![image](https://github.com/Armynerh/html-capstone-project/assets/93520178/26b8fa2c-ce26-42c4-90d7-484735fd595d)

- [ ] I know you gave the appropriate credit to the design owner in your PR description, but it would be great if you could add it in the acknowledgement section of your `README` instead as it was mentionned in the [requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/capstone/html_capstone.md#:~:text=The%20Creative%20Commons%20license%20of%20the%20design%20requires%20that%20you%20give%20appropriate%20credit%20to%20the%20author.%20Therefore%2C%20you%20must%20do%20it%20in%20the%20README%20of%20your%20project.)

- [ ] Nice job deploying your application on github pages, but when navigating to the home page and the about page using the links in the navigation menu, I get a 404 page: 
![image](https://github.com/Armynerh/html-capstone-project/assets/93520178/11903c9b-ea1b-4160-9f12-02e08b2847b8)

- [ ] For your header in the desktop view, there should be the same amount of space on the left side of your logo as there is on the right side of the header: 
    - The design: 
    ![image](https://github.com/Armynerh/html-capstone-project/assets/93520178/ac0cf6bc-b2d4-4028-afee-932081738c83)
    - Your design: 
    ![image](https://github.com/Armynerh/html-capstone-project/assets/93520178/983b1033-91d2-4bde-8803-26b600233686)

- [ ] Kindly make the footer appear in mobile view in your Home page.
- [ ] For the first section of the home  page: 
    - There should be more space on the left sire of the text, 
    - The font sizes of the different blocks of text should match the design: 
         - Your design: 
         ![image](https://github.com/Armynerh/html-capstone-project/assets/93520178/2b0f4a32-eed4-4a52-b405-e55ccc4f2085)
         - The design: 
         ![image](https://github.com/Armynerh/html-capstone-project/assets/93520178/23340e51-5a96-4063-a5ab-480824199d6d)
    - There is too much space between the burger menu and the content of the first section, you should also make the font size on the first line a bit bigger to match the design in mobile view: 
    ![image](https://github.com/Armynerh/html-capstone-project/assets/93520178/cf54098e-9a8d-441c-a146-4b30e1abd292)
 
- [ ] For the program section: 
    - There should be a small divider between the title of the secion and the program cards:
         - Your design:
           ![image](https://github.com/Armynerh/html-capstone-project/assets/93520178/79955832-c008-46c7-adcf-eb945e52d5a7)
         - The design:
         ![image](https://github.com/Armynerh/html-capstone-project/assets/93520178/b65613d1-5e47-4fbe-b2ad-e4dab57d9ed0)

    - There should be a bit more top and bottom padding for each card: 
         - Your design: 
         ![image](https://github.com/Armynerh/html-capstone-project/assets/93520178/d13537cc-4225-4b7f-a3af-64cc59dfcb6d)

         - The design: 
         ![image](https://github.com/Armynerh/html-capstone-project/assets/93520178/a5cd543b-5a29-414a-a6cc-cd969d7bb3d0)

- [ ] For the speakers section: 
    - There is too much spacing between the elements, 
    - There should be a small divider between the header and the speaker cards: 
         - Your design:
         ![image](https://github.com/Armynerh/html-capstone-project/assets/93520178/a11a90f4-ecfa-4db9-b5ed-030ba3722e68)
         - The design: 
         ![image](https://github.com/Armynerh/html-capstone-project/assets/93520178/4b083096-2fb4-499a-b07b-c506a7497d9f)
    - The second column that holds the information about the speaker should contain a title, subtitle, and description: 
         - Your design:
         ![image](https://github.com/Armynerh/html-capstone-project/assets/93520178/ac8596d9-74fa-4a17-9bca-d8a951c02f12)
         - The design: 
         ![image](https://github.com/Armynerh/html-capstone-project/assets/93520178/9e77b042-57be-407b-9924-8a6ee5284178)

- [ ] For the first section of the about page: 
    - The content should be properly centered in desktop view: 
         - Your design: 
         ![image](https://github.com/Armynerh/html-capstone-project/assets/93520178/8644752e-70a5-4c07-ac8f-826c262c57ef)
         - The design: 
         ![image](https://github.com/Armynerh/html-capstone-project/assets/93520178/cb27827c-d860-4ef0-91db-3117e8aab924)
    - There is too much extra space between the elements: 
         - Your design: 
         ![image](https://github.com/Armynerh/html-capstone-project/assets/93520178/53129c98-db3a-43b1-bf3c-207a3728a9ff)
         - The design: 
         ![image](https://github.com/Armynerh/html-capstone-project/assets/93520178/7698678c-cce9-45e0-aa13-09808e14d6a7)

- [ ] The about page needs these two sections: 
    - a middle section with a centered column that includes a section header, a divider, a paragraph of text, and an image or large logo.
    - a bottom section with a centered column that includes a section header, a divider, a line of text, and two images with text centered over them
         - Your design: 
         ![image](https://github.com/Armynerh/html-capstone-project/assets/93520178/c326efd1-6f89-4bed-9b7e-a7381f61268f)
         - The design: 
         ![image](https://github.com/Armynerh/html-capstone-project/assets/93520178/ad254606-9225-4615-8b24-1adb91a12177)

- [ ] There should be only 1 `h1` tag in each HTML file. 
- [ ] As mentioned in the requirements, the content of this site should be customized to the theme you chose, kindly add actual content to the site instead of using `lorem ipsum` text.

_Check the comments under the review :point_down:_

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-07 23:05 UTC, anagudelogu requested changes
# STATUS: CHANGES REQUIRED ♻️ 🚧 

Hi @Armynerh 👋🏼 
I'm Andres.

You've done a great job implementing some of the requested changes for this milestone 🚀, but there are still some which haven't been addressed yet. You're getting closer, keep up the good work! 🤖 🎆 

<img src="https://media2.giphy.com/media/3ohhwi25ISXC7Z4tMs/giphy-downsized-medium.gif"/>

 ## Highlights
✅ Great use of GitHub flow. 💯 
✅ Your project is documented professionally. 📜 
✅ Descriptive PR title, summary and commit messages. 💬 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-07 23:05 UTC, anagudelogu commented on index.html
> +        </section>
- [x] You did a good job working on the changes requested by the previous reviewer. 💯 However, please make sure to follow as closely as possible the given design, the font is tiny, and people with visual disabilities could have problems trying to read it. The content of each speaker should be aligned to the left. Please include a Title, a Subtitle, and a Description for each speaker as suggested by the previous reviewer.

| Your Design |
|---|
| ![Screenshot from 2023-07-07 17-45-58](https://github.com/Armynerh/html-capstone-project/assets/77069011/33782da6-fcf2-497f-a766-a25c08d9f104) |

| Template |
|---|
|![image](https://github.com/Armynerh/html-capstone-project/assets/77069011/35dda4f1-649b-401d-bd55-25cdc998aa9d)|

This also happens in the mobile design:

|Template|Your design|
|---|---|
| ![image](https://github.com/Armynerh/html-capstone-project/assets/77069011/09c40ef5-3746-4ad7-99db-b641b14a5ff4) | ![image](https://github.com/Armynerh/html-capstone-project/assets/77069011/c3cf9827-237e-4625-800d-58982576e5fb) |

Please consider fixing this 🤓 🔧

2023-07-07 23:05 UTC, anagudelogu commented on index.html
> +                    <div class="sf-color"><p>Lorem Ipsum sit dolo met blah blah blah blah blah</p></div>
- [ ] According to the previous review, please consider customizing your content instead of using Lorem Ipsum. In the future, this will come in handy to attract the attention of recruiters! 🤓 🔧

2023-07-08 07:25 UTC, wayungi approved these changes
Hi @Armynerh , 

![image](https://user-images.githubusercontent.com/99656687/220082459-c1b049c7-5498-42e7-942b-ec7a05d3e603.png)

Great work, your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

**Remember: Every finish line 🏁  is the beginning of a new race 🐎** 

## Highlights
- [ ] Well written README ✔️ 
- [ ] All Linter checks passing ✔️ 
- [ ] Project up and running ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-08 07:25 UTC, wayungi commented on index.html
> +            <div class="grid two-column one-column team" >
- [ OPTIONAL] Your speakers' section is not well aligned in the center as in the Figma. Please  fix this inorder to match the Figma design

**DESIGN**
![des1](https://github.com/Armynerh/html-capstone-project/assets/99656687/d5d1863d-b206-4767-8457-83f4603d76eb)

**YOUR IMPLEMENTATION**
![des2](https://github.com/Armynerh/html-capstone-project/assets/99656687/9e969380-9444-45d1-ad6a-aaa999b5475d)

2023-07-08 07:25 UTC, wayungi commented on index.html
> +        </section>
- [ OPTIONAL] Your partner section is aligned vertically while the Figma is aligned horizontally. Kindly align your partners to match the Figma 😺 

**Figma**
![des1](https://github.com/Armynerh/html-capstone-project/assets/99656687/a0a90e9e-82dc-4bb2-a1b5-632f36669bc4)

**Your implemntation**
![des2](https://github.com/Armynerh/html-capstone-project/assets/99656687/5e3f9dde-647a-47b6-a4b2-13c42ee132c5)

2023-07-08 07:31 UTC, merged